package com.lw.methods;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RequestRESDelegate", targetNamespace = "http://methods.lw.com/")
public interface RequestRESDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "requestRES", targetNamespace = "http://methods.lw.com/", className = "com.lw.methods.RequestRES")
	@ResponseWrapper(localName = "requestRESResponse", targetNamespace = "http://methods.lw.com/", className = "com.lw.methods.RequestRESResponse")
	public String requestRES(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
