package com.lw.methods;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RequestRESService service = new RequestRESService();
 * RequestRESDelegate portType = service.getRequestRESPort();
 * portType.requestRES(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RequestRESService", targetNamespace = "http://methods.lw.com/", wsdlLocation = "http://localhost:8080/hsresws/RequestRESPort?wsdl")
public class RequestRESService extends Service {

	private final static URL REQUESTRESSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.lw.methods.RequestRESService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.lw.methods.RequestRESService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/hsresws/RequestRESPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/hsresws/RequestRESPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		REQUESTRESSERVICE_WSDL_LOCATION = url;
	}

	public RequestRESService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RequestRESService() {
		super(REQUESTRESSERVICE_WSDL_LOCATION, new QName(
				"http://methods.lw.com/", "RequestRESService"));
	}

	/**
	 * 
	 * @return returns RequestRESDelegate
	 */
	@WebEndpoint(name = "RequestRESPort")
	public RequestRESDelegate getRequestRESPort() {
		return super.getPort(new QName("http://methods.lw.com/",
				"RequestRESPort"), RequestRESDelegate.class);
	}

}
